

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRUcode[] =  {
     0x240000e1,
     0x240001c4,
     0x24000084,
     0x240010e2,
     0x240000e3,
     0x240000e4,
     0x240000e5,
     0x240000e6,
     0x2400aac7,
     0x24aaaa87,
     0x240000e8,
     0x1f01fefe,
     0x240010e2,
     0x240001e3,
     0x240000e5,
     0x240000e4,
     0x5100e215,
     0x0501e2e2,
     0x0ae2e7e6,
     0x1101e6e6,
     0xc900e303,
     0x60e4e604,
     0x79000005,
     0x60e6e402,
     0x79000003,
     0x0101e3e3,
     0x79000003,
     0x240001e3,
     0x240000e5,
     0x10e6e6e4,
     0x5908e302,
     0x7f0000f1,
     0x240000e3,
     0x0101e5e5,
     0x5903e502,
     0x7f0000ed,
     0x79000001,
     0x1d01fefe,
     0x7f0000e5,
     0x2400231f,
     0x2a000000 };

